spring.application.name=Fitness-Tracker

spring.datasource.deriver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

//secret Key for jwt
jwt.secret=NzI5MzY5ODQ3MjkzNjk4NDcyOTM2OTg0NzI5MzY5ODQ=

spring.profiles.active=dev